# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-01 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loginR', '0007_auto_20170929_1737'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poke',
            name='poked',
        ),
        migrations.DeleteModel(
            name='PokeManager',
        ),
        migrations.AddField(
            model_name='user',
            name='friended',
            field=models.ManyToManyField(related_name='_user_friended_+', to='loginR.User'),
        ),
        migrations.DeleteModel(
            name='Poke',
        ),
    ]
